version: '3.8'

services:
  builder:
    build:
      context: .
      target: builder
    image: my-java-app-builder
    volumes:
      - app_target:/app/target

  tomcat:
    image: tomcat:9.0-jdk11-openjdk
    ports:
      - "8080:8080"
    volumes:
      - app_target:/usr/local/tomcat/webapps
    depends_on:
      - builder
    restart: unless-stopped
volumes:
  app_target:
